name: Test Validation
on:
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - edited
jobs:
  validate:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            chore
          scopes: |
            POD[1-3]-\d+
            PLG-\d+
            PLAT-\d+
            PE-\d+
          requireScope: true
          disallowScopes: |
            release
            [A-Z]+
          ignoreLabels: |
            bot
            ignore-semantic-pull-request