name: Test PR Validations

on:
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - edited

jobs:
  validate:
    name: Validate PR title
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./main

    permissions:
      pull-requests: write

    steps:
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            chore
          scopes: |
            POD[1-3]-\d+
            PLG-\d+
            PLAT-\d+
            PE-\d+
          requireScope: true
        continue-on-error: false

      - name: Setup Node and Run Test
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
